version: "3"
services:
  app:
    build: .
    ports:
      - "18080:8080"
    volumes:
      - .:/app
    depends_on:
      - db
    command: ["./run.sh"]
  db:
    image: mariadb:10.5.8
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: "mysqluser"
      MYSQL_PASSWORD: "mysqlpass"
      MYSQL_ROOT_PASSWORD: "rootpass"
      MYSQL_DATABASE: "auditlogtest"
volumes:
  mysql_data:
